################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2023 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/base:ubuntu-18.04

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	chrpath \
	cpio \
	debianutils \
	diffstat \
	gcc \
	gcc-multilib \
	iputils-ping \
	libegl1-mesa \
	libsdl1.2-dev \
	mesa-common-dev \
	ncurses-dev \
	pigz \
	pylint3 \
	python \
	python3 \
	python3-git \
	python3-jinja2 \
	python3-pexpect \
	python3-pip \
	python3-subunit \
	rsync \
	socat \
	xterm \
	xz-utils \
&& apt-get autoremove --yes && apt-get clean --yes
RUN rm -rf /var/lib/apt/lists/*
