################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021 - 2022 TQ-Systems GmbH <license@tq-group.com>
# author: Martin Schmiedel <martin.schmiedel@tq-group.com>
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/base:ubuntu-20.04

RUN dpkg --add-architecture i386

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	chrpath \
	cpio \
	curl \
	debianutils \
	diffstat \
	gcc \
	iputils-ping \
	libc6:i386 \
	libegl1-mesa \
	libsdl1.2-dev \
	liblz4-tool \
	mesa-common-dev \
	pigz \
	pylint3 \
	python3 \
	python3-git \
	python3-jinja2 \
	python3-pexpect \
	python3-pip \
	python3-subunit \
	python3-yaml \
	rsync \
	socat \
	time \
	xterm \
	xz-utils \
	zstd \
&& apt-get autoremove --yes && apt-get clean --yes
RUN rm -rf /var/lib/apt/lists/*
