################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021 - 2022 TQ-Systems GmbH <license@tq-group.com>
# author: Martin Schmiedel <martin.schmiedel@tq-group.com>
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/ptxdist-base:ubuntu-18.04

# add user
# to enable bind mounts on jenkins slaves
# appropriate users must be added to every jenkins slave

RUN mkdir /home/ptxdist_18; groupadd -g 10002 ptxdist_18; groupadd -g 632 jenkins; \
 	useradd -r -u 10002 -g ptxdist_18 -G jenkins -d /home/ptxdist_18 ptxdist_18; \
	chown ptxdist_18:ptxdist_18 /home/ptxdist_18;

# install java from launchpad (jenkins needs java8)

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	openjdk-8-jre \
&& apt-get autoremove --yes && apt-get clean --yes
