################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021 - 2022 TQ-Systems GmbH <license@tq-group.com>
# author: Martin Schmiedel <martin.schmiedel@tq-group.com>
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/ptxdist-base:ubuntu-14.04

ARG ci_user_name
ARG ci_user_uid
ARG ci_user_gid
ARG ci_java_version

ENV USER=${ci_user_name} USER_ID=${ci_user_uid} USER_GID=${ci_user_gid} \
	JAVA_VERSION=${ci_java_version}

# add user
# to enable bind mounts on jenkins slaves
# appropriate users must be added to every jenkins slave
#
# when using git as patchtool in ptxdist we need 'git init' to have valid
# data in ~/.gitconfig.
# TODO: remove jenkins dependency
RUN \
	groupadd --gid "${USER_GID}" "${USER}" && \
	useradd \
		--uid ${USER_ID} \
		--gid ${USER_GID} \
		--create-home \
		--shell /bin/bash \
		${USER} && \
    git config --file=/home/${USER}/.gitconfig --add user.email "${USER}@autobuild.org" && \
    git config --file=/home/${USER}/.gitconfig --add user.name "${USER}"


# install java from launchpad (jenkins needs java-11)

RUN \
	echo "deb [trusted=yes] http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main" >> /etc/apt/sources.list && \
	apt-get update && apt-get -y upgrade && \
	apt-get install -y \
		${JAVA_VERSION} && \
	apt-get autoremove --yes && apt-get clean --yes && \
	rm -rf /var/lib/apt/lists/*

USER "${USER}"
