################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2023 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

FROM amd64/ubuntu:18.04

# set environment
ENV DEBIAN_FRONTEND=noninteractive

#
# see README in directory
#
RUN echo "Acquire::http::Pipeline-Depth "0";" > /etc/apt/apt.conf.d/docker-tweak

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	bc \
	build-essential \
	file \
	gawk \
	locales \
	texinfo \
	unzip \
	wget \
&& apt-get autoremove --yes && apt-get clean --yes && \
rm -rf /var/lib/apt/lists/*

ADD certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates && rm -f /usr/local/share/ca-certificates/.keepme

RUN locale-gen --lang en_US.UTF-8 && \
	update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8
# update-locale creates /etc/default/locale (used by "su" command or user remapping)
# docker doesn't use etc/default/locale if container uses USER statement for non root user
# therefore ENV has to be be used to set locale variables for derived docker containers
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

ADD base/gitconfig /etc/gitconfig

# install up to date git version
RUN \
	echo "deb [trusted=yes] https://ppa.launchpadcontent.net/git-core/ppa/ubuntu bionic main" >> /etc/apt/sources.list && \
	apt-get update && apt-get -y upgrade && \
	apt-get install -y \
		git && \
	apt-get autoremove --yes && apt-get clean --yes && \
	rm -rf /var/lib/apt/lists/*