################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2024 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/base:ubuntu-22.04

RUN \
	echo "deb [trusted=yes] http://debian.pengutronix.de/debian/ jammy main" >> /etc/apt/sources.list && \
	apt-get update && apt-get -y upgrade && \
	apt-get install -y \
		bison \
		cmake \
		device-tree-compiler \
		flex \
		git-lfs \
		libgnutls28-dev \
		libssl-dev \
		lzop \
		oselas.toolchain-2023.07.1-aarch64-v8a-linux-gnu \
		oselas.toolchain-2023.07.1-arm-v7a-linux-gnueabihf \
		oselas.toolchain-2023.07.1-powerpc-603e-linux-gnu \
		pengutronix-archive-keyring \
		python3 \
		python3-dev \
		python3-jsonschema \
		python3-pip \
		python3-pyelftools \
		python3-setuptools \
		swig \
		tree \
		uuid-dev \
		xz-utils \
		xxd \
		zip \
		zlib1g-dev \
		zstd && \
	apt-get autoremove --yes && apt-get clean --yes && \
	rm -rf /var/lib/apt/lists/*

# zephyr's meta repo management needed for NXP MCU SDK
RUN pip3 install west

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz && \
	tar --xz -xf arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz --directory /opt && \
	rm arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
	
RUN \
	wget https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4-linux-x86_64.tar.gz && \
	tar --gzip -xf cmake-3.27.4-linux-x86_64.tar.gz --directory /opt && \
	rm cmake-3.27.4-linux-x86_64.tar.gz

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz && \
	tar --xz -xf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz --directory /opt && \
	rm arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
	
RUN \
	wget https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-linux-x86_64.tar.gz && \
	tar --gzip -xf cmake-3.29.2-linux-x86_64.tar.gz --directory /opt && \
	rm cmake-3.29.2-linux-x86_64.tar.gz