################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2023 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/base:ubuntu-18.04

RUN \
	echo "deb [trusted=yes] http://debian.pengutronix.de/debian/ bionic main" >> /etc/apt/sources.list && \
	apt-get update && apt-get -y upgrade && \
	apt-get install -y \
		bison \
		cmake \
		device-tree-compiler \
		flex \
		libssl-dev \
		lzop \
		oselas.toolchain-2020.08-aarch64-v8a-linux-gnu \
		oselas.toolchain-2020.08-arm-v7a-linux-gnueabihf \
		oselas.toolchain-2020.08-powerpc-603e-linux-gnu \
		pengutronix-archive-keyring \
		python3 \
		python3-dev \
		python3-pip \
		python3-setuptools \
		swig \
		tree \
		xz-utils \
		xxd \
		zip \
		zlib1g-dev \
		zstd && \
	apt-get autoremove --yes && apt-get clean --yes && \
	rm -rf /var/lib/apt/lists/*

# zephyr's meta repo management needed for NXP MCU SDK
RUN pip3 install west

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz && \
	tar --xz -xf arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz --directory /opt && \
	rm arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
	
RUN \
	wget https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4-linux-x86_64.tar.gz && \
	tar --gzip -xf cmake-3.27.4-linux-x86_64.tar.gz --directory /opt && \
	rm cmake-3.27.4-linux-x86_64.tar.gz
