################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2024 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

ARG registry_base_url=registry.example.com:5005/registry-path
FROM ${registry_base_url}/base:ubuntu-24.04

# Large packages should come first
RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz && \
	tar --xz -xf arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz --directory /opt && \
	rm arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
	
RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 && \
	tar -jxf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 --directory /opt && \
	rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2

RUN \
	wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz && \
	tar --xz -xf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz --directory /opt && \
	rm arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
	
RUN \
	wget https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-linux-x86_64.tar.gz && \
	tar --gzip -xf cmake-3.31.4-linux-x86_64.tar.gz --directory /opt && \
	rm cmake-3.31.4-linux-x86_64.tar.gz

# ninja for up to date NXP SDK
RUN \
	wget https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip && \
	mkdir -p /opt/ninja-v1.12.1 && \
	gunzip -c ninja-linux.zip > /opt/ninja-v1.12.1/ninja && \
	rm ninja-linux.zip && \
	chmod ugoa+x /opt/ninja-v1.12.1/ninja

#compilers are also large and seldom updated
RUN \
	echo "deb [trusted=yes] http://debian.pengutronix.de/debian/ noble main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get install -y \
		oselas.toolchain-2024.11.1-aarch64-v8a-linux-gnu \
		oselas.toolchain-2024.11.1-arm-v7a-linux-gnueabihf \
		oselas.toolchain-2024.11.1-powerpc-603e-linux-gnu \
		pengutronix-archive-keyring

RUN \
	echo "deb [trusted=yes] http://debian.pengutronix.de/debian/ jammy main" >> /etc/apt/sources.list && \
	apt-get update && apt-get -y upgrade && \
	apt-get install -y \
		bison \
		cmake \
		device-tree-compiler \
		flex \
		git-lfs \
		libgnutls28-dev \
		libssl-dev \
		lzop \
		pipx \
		python3 \
		python3-dev \
		python3-importlib-resources \
		python3-jsonschema \
		python3-pip \
		python3-pyelftools \
		python3-setuptools \
		python3-venv \
		swig \
		tree \
		uuid-dev \
		xz-utils \
		xxd \
		zip \
		zlib1g-dev \
		zstd && \
	apt-get autoremove --yes && apt-get clean --yes && \
	rm -rf /var/lib/apt/lists/*

# zephyr's meta repo management and python kconfig library needed for NXP MCU SDK
RUN \
	pipx install west && \
	pipx install kconfiglib
