################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2023 TQ-Systems GmbH <oss@ew.tq-group.com>
# author: Martin Schmiedel
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/bare-base:ubuntu-18.04

ARG ci_user_name
ARG ci_user_uid
ARG ci_user_gid

ENV USER=${ci_user_name} USER_ID=${ci_user_uid} USER_GID=${ci_user_gid}

# add user
# to enable bind mounts on jenkins slaves
# appropriate users must be added to every jenkins slave

RUN \
	groupadd --gid "${USER_GID}" "${USER}" && \
	useradd \
		--uid ${USER_ID} \
		--gid ${USER_GID} \
		--create-home \
		--shell /bin/bash \
		${USER}

COPY bare/.buildman /home/${USER}/
COPY bare/.gitconfig /home/${USER}/

RUN git clone --depth=1 --branch TQM-v2021.10 https://github.com/tq-systems/u-boot-tqmaxx.git /home/${USER}/u-boot

USER "${USER}"
