################################################################################
# SPDX-License-Identifier: MIT
# Copyright (c) 2021 - 2022 TQ-Systems GmbH <license@tq-group.com>
# author: Martin Schmiedel <martin.schmiedel@tq-group.com>
################################################################################

ARG registry_base_url
FROM ${registry_base_url}/base:ubuntu-18.04

RUN echo "deb [trusted=yes] http://debian.pengutronix.de/debian/ bionic main" >> /etc/apt/sources.list

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	bash-completion \
	bison \
	device-tree-compiler \
	flex \
	libssl-dev \
	oselas.toolchain-2020.08-aarch64-v8a-linux-gnu \
	oselas.toolchain-2020.08-arm-v7a-linux-gnueabihf \
	oselas.toolchain-2020.08-powerpc-603e-linux-gnu \
	pengutronix-archive-keyring \
	python3 \
	tree \
	xz-utils \
	zip \
	zlib1g-dev \
&& apt-get autoremove --yes && apt-get clean --yes
RUN rm -rf /var/lib/apt/lists/*

COPY tqma8/.buildman /root

RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 && tar -jxf gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 --directory /opt

RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 && tar -jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 --directory /opt

RUN git clone --branch v2021.10 https://source.denx.de/u-boot/u-boot.git /root/u-boot
